//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/MirControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MirControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MirControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MirControls"",
    ""maps"": [
        {
            ""name"": ""MirPlayer"",
            ""id"": ""0e30a9fa-bd73-4034-bb49-cf792525b912"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""1b902cea-566e-45bf-a0e7-c50898054df6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3dae5e94-ddb3-440e-bfaf-28db7c70564c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MirPlayer
        m_MirPlayer = asset.FindActionMap("MirPlayer", throwIfNotFound: true);
        m_MirPlayer_Newaction = m_MirPlayer.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MirPlayer
    private readonly InputActionMap m_MirPlayer;
    private IMirPlayerActions m_MirPlayerActionsCallbackInterface;
    private readonly InputAction m_MirPlayer_Newaction;
    public struct MirPlayerActions
    {
        private @MirControls m_Wrapper;
        public MirPlayerActions(@MirControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_MirPlayer_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_MirPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MirPlayerActions set) { return set.Get(); }
        public void SetCallbacks(IMirPlayerActions instance)
        {
            if (m_Wrapper.m_MirPlayerActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_MirPlayerActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_MirPlayerActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_MirPlayerActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_MirPlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public MirPlayerActions @MirPlayer => new MirPlayerActions(this);
    public interface IMirPlayerActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
